name: Build APK
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build with Buildozer
        # Hum official Kivy buildozer action use karenge jo stable hai
        uses: ArtemSerebrennkov/buildozer-action@v1.6.1
        with:
          buildozer_version: master
          python_version: 3.10

      - name: Upload APK
        # Naya version v4 use kar rahe hain
        uses: actions/upload-artifact@v4
        with:
          name: PrishVault-APK
          path: bin/*.apk
